setting up CRAN mirror early on

diff --git a/containers/debian/Dockerfile b/containers/debian/Dockerfile
--- a/containers/debian/Dockerfile
+++ b/containers/debian/Dockerfile
@@ -58,6 +58,16 @@ ENV PATH="/opt/R-$R_VERSION/bin:${PATH}"
 ENV CPLUS_INCLUDE_PATH="/usr/include/c++/13:/usr/include/x86_64-linux-gnu/c++/13"
 ENV C_INCLUDE_PATH="/usr/include"
 
+# Set CRAN mirror (must happen before any R package installs)
+RUN R_HOME=$(R RHOME) && \
+    if [ -d "${R_HOME}/library/base/R" ]; then \
+      echo 'options(repos = c(CRAN = "https://cran.rstudio.com"))' >> ${R_HOME}/library/base/R/Rprofile; \
+    elif [ -d "${R_HOME}/etc" ]; then \
+      echo 'options(repos = c(CRAN = "https://cran.rstudio.com"))' >> ${R_HOME}/etc/Rprofile.site; \
+    else \
+      echo "ERROR: Could not find R profile location" >&2; exit 1; \
+    fi
+
 # Install rjags (JAGS is available as system package on debian)
 RUN R -e "install.packages('rjags'); if (!requireNamespace('rjags', quietly=TRUE)) stop('Failed to install: rjags')"
 
diff --git a/containers/fedora/Dockerfile b/containers/fedora/Dockerfile
--- a/containers/fedora/Dockerfile
+++ b/containers/fedora/Dockerfile
@@ -61,6 +61,16 @@ RUN dnf -y install \
 # Add R to PATH
 ENV PATH="/opt/R-$R_VERSION/bin:${PATH}"
 
+# Set CRAN mirror (must happen before any R package installs)
+RUN R_HOME=$(R RHOME) && \
+    if [ -d "${R_HOME}/library/base/R" ]; then \
+      echo 'options(repos = c(CRAN = "https://cran.rstudio.com"))' >> ${R_HOME}/library/base/R/Rprofile; \
+    elif [ -d "${R_HOME}/etc" ]; then \
+      echo 'options(repos = c(CRAN = "https://cran.rstudio.com"))' >> ${R_HOME}/etc/Rprofile.site; \
+    else \
+      echo "ERROR: Could not find R profile location" >&2; exit 1; \
+    fi
+
 # Build and install JAGS from source
 # Fedora does not package JAGS, so we compile it matching R's compiler and BLAS/LAPACK.
 # See https://usermanual.wiki/Document/jagsinstallationmanual.880863585.pdf
diff --git a/containers/valgrind/Dockerfile b/containers/valgrind/Dockerfile
--- a/containers/valgrind/Dockerfile
+++ b/containers/valgrind/Dockerfile
@@ -60,6 +60,16 @@ ENV PATH="/opt/DrMemory/DrMemory-Linux-$DRMEMORY/bin:${PATH}"
 # Add R to PATH (valgrind R is installed at a fixed path)
 ENV PATH="/opt/R/devel-valgrind/bin:${PATH}"
 
+# Set CRAN mirror (must happen before any R package installs)
+RUN R_HOME=$(R RHOME) && \
+    if [ -d "${R_HOME}/library/base/R" ]; then \
+      echo 'options(repos = c(CRAN = "https://cran.rstudio.com"))' >> ${R_HOME}/library/base/R/Rprofile; \
+    elif [ -d "${R_HOME}/etc" ]; then \
+      echo 'options(repos = c(CRAN = "https://cran.rstudio.com"))' >> ${R_HOME}/etc/Rprofile.site; \
+    else \
+      echo "ERROR: Could not find R profile location" >&2; exit 1; \
+    fi
+
 # Build and install JAGS from source
 # See https://usermanual.wiki/Document/jagsinstallationmanual.880863585.pdf
 ADD https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Source/$JAGS.tar.gz/download /tmp/jags.tar.gz
