feature: adding development workflow (#44)
* addign dev workflow

* defining vars in repo not workflow

* renaming

* run on label build::check

* fixing workflow name and other stirngs

* added job to set outcome label

* fixing dependency of final job reporting outcome

* fixing typo; always try to run integrity

diff --git a/.github/workflows/onlabel_check_build.yml b/.github/workflows/onlabel_check_build.yml
--- a/.github/workflows/onlabel_check_build.yml
+++ b/.github/workflows/onlabel_check_build.yml
@@ -1,12 +1,16 @@
-name: Create Docker image and publish to GH Packages
+# Workflow triggered when labeling a pull request with `build::check`
+# This action is adapted from https://github.com/t4d-gmbh/stubbed_versioning
+name: Check Container Builds
 
 on:
-  push:
-    branches: [ main ]    # create a new version whenever we push to main
-  schedule:
-    - cron: "12 2 2 * *"  # run at 2:12 of the 2nd of every month
+  pull_request:
+    types: [ labeled ]
 
 env:
+  LABEL_CHECK: 'build::check'
+  LABEL_SUCCESS: 'build::passed'
+  LABEL_FAILURE: 'build::failed'
+
   DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}  # where to register the image
   REPO_PATH: ${{ vars.REPO_PATH }}
   # REPO_PATH: github.com:furrer-lab/abn.git  # for private repo cloned via ssh
@@ -20,25 +24,8 @@ env:
 
 jobs:
 
-  increment-tag:
+  build:
     runs-on: ubuntu-latest
-    permissions:
-      contents: write
-    outputs:
-      VERSION: ${{ steps.version.outputs.version }}
-    steps:
-    - uses: actions/checkout@v4
-      with:
-        fetch-depth: '0'
-    - name: Auto increment calver version
-      uses: reecetech/version-increment@2023.10.1
-      id: version
-      with:
-        scheme: calver
-
-  build-and-push:
-    runs-on: ubuntu-latest
-    needs: increment-tag
     env:
       CUSTOM_TAG: "${{ needs.increment-tag.outputs.VERSION }}"
     permissions:                       # for `GITHUB_TOKEN`
@@ -94,7 +81,7 @@ jobs:
         uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
         with:
           context: ${{ format('./containers/{0}/', matrix.target-os ) }}
-          push: true
+          push: false
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
           build-args: |
@@ -108,9 +95,11 @@ jobs:
           # For private repo cloned via ssh
           # secret-files: |
           #   key=./ssh_key
+
   container-integrity-and-config:
+    if: ${{ (success() || failure()) }}
     runs-on: ubuntu-22.04
-    needs: [ 'increment-tag', 'build-and-push']
+    needs: [ 'build' ]
     permissions:
       contents: write
       packages: read
@@ -158,61 +147,81 @@ jobs:
         name: info-artifact-${{ matrix.target-os }}_${{ matrix.compiler }}_${{ matrix.r-version }}
         path: info/${{ matrix.target-os }}-${{ matrix.compiler }}-${{ matrix.r-version }}-abn.md
 
-  update-container-info:
+  report_build_check:
+    if: ${{ (success() || failure()) }}
+    needs:
+      - container-integrity-and-config
     runs-on: ubuntu-latest
-    needs: [ 'increment-tag', 'container-integrity-and-config' ]
     permissions:
       contents: write
+      pull-requests: write
+      repository-projects: write
+    env:
+      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      OWNER: ${{ github.repository_owner }}
+      REPO: ${{ github.event.repository.name }}
     steps:
-    - uses: actions/checkout@v4
-      with:
-        fetch-depth: '0'
-    - name: Getting artifacts
-      uses: actions/download-artifact@v4
-      with:
-        pattern: "info-artifact-*"
-        path: info/
-        merge-multiple: true
-    - name: Update the archive
-      run: |
-        mkdir -p info/archive/${{ needs.increment-tag.outputs.VERSION }}
-        cp info/*.md info/archive/${{ needs.increment-tag.outputs.VERSION }}/
-    - name: Commit config for container
-      uses: EndBug/add-and-commit@v9
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      with:
-        pull: '--rebase --autostash'
-        push: true
-        default_author: github_actions
-        message: "auto-update: container info for release ${{ needs.increment-tag.outputs.VERSION }}"
-        add: "info/"
+      - uses: actions/checkout@v4
+      - name: Check if on demand tasks succeeded
+        run: |
+          gh pr edit ${{ env.EVENT }} --remove-label ${{ env.LABEL_CHECK }} --repo ${{ env.OWNER }}/${{ env.REPO }}
+          if [ ${{ needs.container-integrity-and-config.result }} == "success" ]; then
+            gh pr edit ${{ env.EVENT }} --remove-label ${{ env.LABEL_FAILURE }} --repo ${{ env.OWNER }}/${{ env.REPO }}
+            gh pr edit ${{ env.EVENT }} --add-label ${{ env.LABEL_SUCCESS }} --repo ${{ env.OWNER }}/${{ env.REPO }}
+            echo "### ${{ github.event.label.url }} passed! :rocket:" >> $GITHUB_STEP_SUMMARY
+            exit 0
+          elif [ ${{ needs.container-integrity-and-config.result }} == "failure" ]; then
+            gh pr edit ${{ env.EVENT }} --remove-label ${{ env.LABEL_SUCCESS }} --repo ${{ env.OWNER }}/${{ env.REPO }}
+            gh pr edit ${{ env.EVENT  }} --add-label ${{ env.LABEL_FAILURE }} --repo ${{ env.OWNER }}/${{ env.REPO }}
+            echo "### ${{ github.event.label.url }} failed!" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          else
+            gh pr edit ${{ env.EVENT }} --add-label ${{ env.LABEL_CHECK }} --repo ${{ env.OWNER }}/${{ env.REPO }}
+            echo "Container build task outcome was: ${{ steps.container-integrity-and-config.outcome }}"
+          fi
+        shell: bash
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          EVENT: ${{ github.event.number }}  # This is either the issue or pr
 
-  auto-update-and-publish-tag:
+  record_existing_label:
     runs-on: ubuntu-latest
-    needs: [ 'increment-tag', 'update-container-info']
+    env:
+      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      OWNER: ${{ github.repository_owner }}
+      REPO: ${{ github.event.repository.name }}
     permissions:
       contents: write
+      pull-requests: write
+      repository-projects: write
+    outputs:
+      passed: ${{ steps.passed.outputs.PASSED}}
     steps:
-    - uses: actions/checkout@v4
-      with:
-        fetch-depth: '0'
-    - name: Get git-chglog and update CHANGELOG
-      run: |
-        wget ${{ env.CHGLOG_PATH }}/${{ env.CHGLOG_RELEASE}}.tar.gz  # get the binary for the chglog
-        tar --extract --file=${{ env.CHGLOG_RELEASE}}.tar.gz git-chglog
-        git config user.email "actions@github.com"
-        git config user.name "github_actions"
-        git tag -a ${{ needs.increment-tag.outputs.VERSION }} -m 'interim tag for changelog'
-        ./git-chglog -o CHANGELOG.md  # update the changelog file
-        git tag -d ${{ needs.increment-tag.outputs.VERSION }}  # remove the tag again
-    - name: Commit CHANGELOG.md update
-      uses: EndBug/add-and-commit@v9
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      with:
-        pull: '--rebase --autostash'
-        default_author: github_actions
-        message: "auto-update: CHANGELOG.md"
-        add: 'CHANGELOG.md'
-        tag: "${{ needs.increment-tag.outputs.VERSION }}"
+      - name: Check if the pull request is labeled with ${{ env.LABEL_SUCCESS }}  # 2
+        id: passed
+        run: |
+          if $( gh pr view ${{ env.EVENT }} --repo ${{ env.OWNER }}/${{ env.REPO }} --json "labels" --jq ".[].[].name" | grep --quiet ${{ env.LABEL_SUCCESS }}); then
+            echo "PASSED=true" >> $GITHUB_OUTPUT
+          else
+            echo "PASSED=false" >> $GITHUB_OUTPUT
+          fi
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          EVENT: ${{ github.event.number }}  # This is either the issue or pr
+
+  build_check_passed:
+    if: ${{ always() }}
+    needs:
+      - record_existing_label
+      - container-integrity-and-config
+    runs-on: ubuntu-latest
+    env:
+      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      OWNER: ${{ github.repository_owner }}
+      REPO: ${{ github.event.repository.name }}
+    steps:
+      - name: Assert that either checks passed or the label is present
+        run: |
+          if [[ ${{ needs.build.result }} == 'success' || ${{ needs.record_passed_label.outputs.passed }} == 'true' ]]; then
+            echo 'The images were built successfully!';
+          else exit 1; fi
